[project]
name = 'multisig-vault'
description = 'Multi-signature vault system on Stacks'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.multisig]
path = 'contracts/multisig.clar'
clarity_version = 3
# Note: Set to 3 for local testing (Clarinet limitation)
# For mainnet deployment: Manually edit deployment plan to use clarity-version: 4
# Clarity 4 code will work on mainnet even if local tools don't fully support it
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'

